server:
  servlet:
    context-path: /api

spring:
  # mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:hurr_cook}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password:
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000ms

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 24
    refresh-expiration: 720 # 24(h)*30(day)

  oauth:
    kakao:
      client-id: ${REST_API_KEY}
      client-secret: ${CLIENT_SECRET}
      redirect-uri: ${REDIRECT_URI}
